# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            pip install pip
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - run:
          command: |
            mypy fastmri
          name: Check Typing
      - run:
          name: Install fastMRI
          command: |
            python setup.py bdist_wheel
            pip install dist/*.whl
      - run:
          command: |
            echo -e "PyTorch \c" && pip show torch | grep Version 
            pytest --version
            pytest tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
